### ISSUE TITLE
since 1.4.3 and 1.4.4 dont work   ;-( 

### ISSUE THREAD

**Issue by steflp** [mehul0810/wp-distraction-free-view#11]
Hello  your plugin doesnt work since 1.4.3 version
Missing css and jss file due to directory not good !
/wp-content/plugins/wp-distraction-free-view/assets/dist 

/wp-content/plugins/wp-distraction-free-view/assets/src  ????

Can you see that  ? 
thanks

**Comment by mehul0810** [comment]
@steflp I will take a look and update here. If there is any fix required, then I will release a new version.

**Comment by mehul0810** [comment]
@steflp  This issue has been resolved in release `1.5.0`. 

Closing the issue for now. Feel free to reopen if the issue still persists.
