### ISSUE TITLE
choice in post / pages / CPT

### ISSUE THREAD

**Issue by steflp** [mehul0810/wp-distraction-free-view#16]
Hello, 
I use your  plugin in 1 webiste and is it possible to have the choice  : Post / custom Post Type  /page  ? 
When I  activate plugin  , the shortcode are on all pages  ....( home page  too !!!)

Thanks a lot 
Stephane
Example in home page : 
![image](https://user-images.githubusercontent.com/3442544/114899991-bb5e0380-9e13-11eb-9723-a82e621c33a0.png)

**Comment by mehul0810** [comment]
@steflp Thanks for your suggestion.

I will schedule it for next release which would be released by the end of this month.

**Comment by steflp** [comment]
ok thanks on the next release

**Comment by steflp** [comment]
Hello , can you tell me when your plugin will be update ?  for post  /page  / custom post  content ?
Thanks  ;)

**Comment by mehul0810** [comment]
@steflp I have already completed working on it around 75%. I will probably be able to release it by the end of this month.
